/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BackgroundDecoration: typeof import('./src/components/BackgroundDecoration.vue')['default']
    ChatMessage: typeof import('./src/components/Chat/ChatMessage.vue')['default']
    DotAnimation: typeof import('./src/components/DotAnimation.vue')['default']
    GameBoard: typeof import('./src/components/GameBoard/GameBoard.vue')['default']
    GameChat: typeof import('./src/components/Chat/GameChat.vue')['default']
    GameModeSelect: typeof import('./src/components/GameModeSelect.vue')['default']
    InvitationCode: typeof import('./src/components/InvitationCode.vue')['default']
    LoadingClient: typeof import('./src/components/LoadingClient.vue')['default']
    MyButton: typeof import('./src/components/MyButton.vue')['default']
    MyDivider: typeof import('./src/components/MyDivider.vue')['default']
    MyInput: typeof import('./src/components/MyInput.vue')['default']
    NoNetwork: typeof import('./src/components/NoNetwork.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TicTacToeBoard: typeof import('./src/components/GameBoard/TicTacToe/TicTacToeBoard.vue')['default']
    TicTacToeSquare: typeof import('./src/components/GameBoard/TicTacToe/TicTacToeSquare.vue')['default']
  }
}
